# Generated by Django 4.0.3 on 2022-03-28 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_userinfo_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=25)),
                ('roomDescription', models.CharField(max_length=25)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('roomId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_transaction', models.DateField(auto_now=True)),
                ('transactionId', models.CharField(max_length=25)),
                ('remarks', models.TextField(max_length=200)),
                ('roomid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
                ('tenantid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
        ),
    ]
