# Generated by Django 4.0.3 on 2022-04-27 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_alter_roomsassign_tenantid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_transaction', models.DateField(auto_now=True)),
                ('transactionId', models.CharField(max_length=25)),
                ('remarks', models.TextField(max_length=200)),
                ('roomName', models.CharField(max_length=25)),
                ('roomDescription', models.CharField(max_length=25)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('roomid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
                ('tenantid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
