# Generated by Django 4.0.3 on 2022-04-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_joinroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='date_transaction',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='roomDescription',
        ),
        migrations.RemoveField(
            model_name='joinroom',
            name='transactionId',
        ),
    ]
