# Generated by Django 4.0.3 on 2022-04-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_joinroom_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
