# Generated by Django 4.0.3 on 2022-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_joinroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='date_transaction',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='firstname',
            field=models.CharField(default='your first name', max_length=25),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='lastname',
            field=models.CharField(default='your last name', max_length=25),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='remarks',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='roomDescription',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='joinroom',
            name='transactionId',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='joinroom',
            name='roomName',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
