# Generated by Django 4.0.3 on 2022-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_joinroom_capacity_joinroom_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsassign',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
