# Generated by Django 4.0.3 on 2022-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomsassign_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsassign',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roomsassign',
            name='transactionId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
