# Generated by Django 4.0.3 on 2022-05-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_credit_formonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='crname',
            field=models.CharField(choices=[('Chores', 'Chores'), ('Groceries', 'Groceries'), ('Other', 'Other')], default='Chores', max_length=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='foryear',
            field=models.CharField(blank=True, choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=4, null=True),
        ),
    ]
