# Generated by Django 4.0.3 on 2022-03-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utid', models.CharField(blank=True, max_length=25, null=True)),
                ('utname', models.CharField(choices=[('a', 'PGE'), ('b', 'Water'), ('c', 'TV/Cable'), ('d', 'WIFI'), ('e', 'Groceries'), ('f', 'Other')], default='PGE', max_length=10)),
                ('accountid', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_utcreated', models.DateField()),
                ('date_due', models.DateField()),
                ('utdescription', models.TextField(max_length=200)),
            ],
        ),
    ]
