# Generated by Django 4.0.3 on 2022-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_utilities_utid_utilities_formonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='foryear',
            field=models.CharField(blank=True, choices=[('a', '2022'), ('b', '2023'), ('c', '2024')], default='2022', max_length=4, null=True),
        ),
    ]
