# Generated by Django 4.0.3 on 2022-04-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_utilities_foryear_alter_utilities_utname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('formonth', models.IntegerField(blank=True, null=True)),
                ('foryear', models.CharField(blank=True, max_length=4, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
