# Generated by Django 4.0.3 on 2022-05-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_monthlydue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyDue',
        ),
    ]
