# Generated by Django 4.0.3 on 2022-04-03 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formonth', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('foryear', models.CharField(blank=True, choices=[('a', '2022'), ('b', '2023'), ('c', '2024')], default='2022', max_length=4, null=True)),
                ('bill_type', models.CharField(choices=[('All', 'All'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Others', 'Others')], default='All', max_length=10)),
                ('accountid', models.CharField(max_length=25)),
                ('paidamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_paid', models.DateField()),
                ('date_due', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
