# Generated by Django 4.0.3 on 2022-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_date_due_alter_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bill_type',
            field=models.CharField(choices=[('All', 'All'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Deposit', 'Deposit'), ('Others', 'Others')], default='All', max_length=10),
        ),
    ]
