# Generated by Django 4.0.3 on 2022-04-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_foryear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='foryear',
            field=models.CharField(blank=True, choices=[('a', '2022'), ('b', '2023'), ('c', '2024')], default='2022', max_length=4, null=True),
        ),
    ]
